#!/usr/bin/env bash

set -x

. hooks/common

if echo "$GIT_MSG" | grep "build: $whoami"; then

    short_rev=$(git rev-parse --short HEAD)

    image_name="$maintainer/$whoami:$DOCKER_TAG"

    docker push "$image_name"

    docker tag "$image_name" \
        "$maintainer/$whoami:$short_rev"

    docker push "$maintainer/$whoami:$short_rev"

    for tag in $(git tag -l --points-at HEAD); do

        docker tag "$image_name" \
            "$maintainer/$whoami:$tag"

        docker push "$maintainer/$whoami:$tag"
    done

fi
